### ISSUE TITLE
Cli dsl for endpoint urls

### ISSUE THREAD

**Issue by anti-social** [anti-social/json-exporter#1]
**Motivation:**

Original [elasticsearch exporter](https://github.com/justwatchcom/elasticsearch_exporter#configuration) has some options to control endpoints:
- `es.all` - if true, query stats for all nodes in the cluster
- `es.cluster_settings` - if true, query stats for cluster settings
- `es.indices` - if true, query stats for all indices in the cluster
- `es.shards` - if true, query stats for all indices in the cluster, including shard-level stats
- `es.indices_settings` - if true, query settings stats for all indices in the cluster
- `es.snapshots` - if true, query stats for the cluster snapshots

When you specify those options the exporter can enable corresponding endpoint and configure its url.

**Description**

We also should have those endpoints are configured but are disabled by default.

At the moment it is possible to form an endpoint url from predefined parts:

```yaml
- id: nodes
  url: local?groups
  url_parts:
    paths:
      local: /_nodes/_local/stats
      all: /_nodes/stats
    params:
      groups:
        name: groups
        value: _all
```

In this case `local?groups` will form `/_nodes/_local/stats?group=_all` url. 

We can override url using `--endpoint-url` option:
- `--endpoint-url nodes:all` will produce `/_nodes/stats?groups=_all`
- `--endpoint-url 'nodes:all?'` - `/_nodes/stats`

What should be implemented:
- disable any endpoint, for example with `nodes:-`
- endpoint can be disabled by default and then enabled, `nodes:+`
- disable single url parameter, `nodes:?-groups`

Consider how that DSL might look like.

Use [nom](https://docs.rs/nom/6.1.2/nom/index.html) to parse DSL.
